#!/bin/sh

export SCALINGSDATEST_HOME="${SCALINGSDATEST_HOME:-$PWD}"

if [ ! -e "$SCALINGSDATEST_HOME" ]
then
    echo "$SCALINGSDATEST_HOME does not exist" 1>&2
    exit 1
fi

JAR="$SCALINGSDATEST_HOME/scalingsdatests.jar"
CLASS="it.polimi.modaclouds.scalingsdatests.Main"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    SCALINGSDATEST_HOME=`cygpath -w "$SCALINGSDATEST_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

#exec java  $JVM_ARGS -jar "$JAR" "$@"
exec java $JVM_ARGS -cp "$JAR:lib/*" $CLASS "$@"