#!/bin/bash

cd

rm .bashrc_httpagent
touch .bashrc_httpagent

if [ -z ${BASHRC_SET+x} ]
then
    echo "source ~/.bashrc_httpagent" >> ~/.bashrc
    echo "export BASHRC_SET=true" >> ~/.bashrc
fi

bash ~/installHTTPAgent
bash ~/installImperialDC

cd
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
