#!/bin/bash

cd

rm .bashrc_httpagent

bash ~/installHTTPAgent
bash ~/installImperialDC

cd
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
