#!/bin/bash

echo "export MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_ID=http-agent-helper" >> ~/.bashrc_httpagent
echo "export MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_TYPE=HTTPAgentHelper" >> ~/.bashrc_httpagent
echo "export MODACLOUDS_TOWER4CLOUDS_VM_ID=HTTPAgentHelper1" >> .bashrc_httpagent
echo "export MODACLOUDS_TOWER4CLOUDS_VM_TYPE=Frontend" >> .bashrc_httpagent
echo "export MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_TYPE=IaaS" >> .bashrc_httpagent

source /home/ubuntu/.bashrc

sudo rm /home/ubuntu/imperial_dc.log
nohup java -Djava.library.path=/home/ubuntu/hyperic-sigar-1.6.4/sigar-bin/lib/ -jar /home/ubuntu/data-collector.jar tower4clouds >> /home/ubuntu/imperial_dc.log 2>&1 &
sleep 5
disown
