#!/bin/bash

cd

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

sudo apt-get install default-jre -q -y
export JAVA_HOME=/usr/lib/jvm/default-java
echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc_client

sudo apt-get install unzip -q -y

curl "http://mirror.nohup.it/apache//jmeter/binaries/apache-jmeter-2.13.zip" -O
unzip apache-jmeter-2.13.zip

curl "http://jmeter-plugins.org/downloads/file/JMeterPlugins-Standard-1.3.0.zip" -O -L
unzip JMeterPlugins-Standard-1.3.0.zip -d JMeterPlugins-Standard-1.3.0

cp JMeterPlugins-Standard-1.3.0/lib/ext/* apache-jmeter-2.13/lib/ext/
