#!/bin/bash

cd

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

sudo apt-get install default-jre -q -y
export JAVA_HOME=/usr/lib/jvm/default-java
echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc_client

sudo apt-get install unzip -q -y

curl "http://mirror.nohup.it/apache//jmeter/binaries/apache-jmeter-2.13.zip" -o "apache-jmeter.zip"
unzip apache-jmeter

curl "http://jmeter-plugins.org/downloads/file/JMeterPlugins-Standard-1.3.0.zip" -o "JMeterPlugins-Standard.zip"
unzip JMeterPlugins-Standard

cp JMeterPlugins-Standard/lib/ext/JMeterPlugins-Standard.jar apache-jmeter/lib/ext/
