#!/bin/bash

cd

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | \
      sudo tee /etc/apt/sources.list.d/backports.list
sudo apt-get update -y
sudo apt-get install -y haproxy -t trusty-backports

sudo service haproxy stop
sudo mv /etc/haproxy/haproxy.cfg{,.original}

echo "global
    log 127.0.0.1 local0 notice
    maxconn 10000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen webapp 0.0.0.0:8080
    mode http
    stats enable
    stats uri /haproxy?stats
    stats realm Strictly\ Private
    stats auth modaclouds:modaclouds
    balance roundrobin
    option http-server-close
    timeout http-keep-alive 3000
    option forwardfor
    cookie SESSID prefix
    server webapp1 10.0.0.1:8080 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "\$ModLoad imudp
\$UDPServerAddress 127.0.0.1
\$UDPServerRun 514" | sudo tee -a /etc/rsyslog.conf

sudo service rsyslog restart

source ~/.bashrc_lb
cd
