#!/bin/bash

cd

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | \
      sudo tee /etc/apt/sources.list.d/backports.list
sudo apt-get update -y
sudo apt-get install -y haproxy -t trusty-backports

sudo service haproxy stop
sudo service haproxy disable

echo "
frontend fwebapp
    bind *:REPLACE_PORT
    mode http
    default_backend bwebapp

backend bwebapp
    mode http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
    cookie SRV_ID prefix
    REPLACE_SERVER

listen stats *:1936
    stats enable
    stats uri /
    stats hide-version
    stats auth modaclouds:modaclouds" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "\$ModLoad imudp
\$UDPServerAddress 127.0.0.1
\$UDPServerRun 514" | sudo tee -a /etc/rsyslog.conf

sudo service rsyslog restart

sudo apt-get install -y git sqlite3 python-pip
cd
git clone https://github.com/igabriel85/modaclouds-loadbalancer-controller.git
sudo pip install virtualenv
cd modaclouds-loadbalancer-controller
rm -rf envHrapi
virtualenv envHrapi
/bin/bash -c "source envHrapi/bin/activate; exec pip install -r requirements.txt"

echo "
* soft nofile 100000
* hard nofile 100000" | sudo tee -a /etc/security/limits.conf

echo "
fs.file-max = 100000" | sudo tee -a /etc/sysctl.conf

sudo sh -c "ulimit -n 100000"

source ~/.bashrc_lb
cd
