#!/bin/bash
#$1=LB PORT
#$2->$INF=IP:PORT OF THE SERVERS

FILE="/etc/haproxy/haproxy.cfg"
TMP_FILE="/tmp/haproxy.cfg"
PORT=8080
if [ "$#" -gt 0 ]
then
    PORT=$1
fi

if [ ! -f "$FILE-prestart" ]
then
    sudo cp "$FILE" "$FILE-prestart"
fi

sudo cp "$FILE-prestart" "$FILE"

sed "s/REPLACE_PORT/$PORT/" <$FILE >$TMP_FILE

shift
for server in "$@"
do
    sed "s/REPLACE_SERVER/server app $server cookie checkNEWLINE    REPLACE_SERVER/" <$TMP_FILE >$TMP_FILE-1
    sed 's/NEWLINE/\
/g' <$TMP_FILE-1 >$TMP_FILE
done
sed "s/REPLACE_SERVER//" <$TMP_FILE >$TMP_FILE-1
mv $TMP_FILE-1 $TMP_FILE
sudo mv $TMP_FILE $FILE

sudo service haproxy restart
