#!/bin/bash
#$1=MP-IP
#$2=SDA-IP
#$3=CPU NUMBER
#$4=DEMAND ESTIMATOR
#$5=SDA WINDOW

PREV1=`expr 300 / $5`
PREV2=`expr 600 / $5`
PREV3=`expr 900 / $5`
PREV4=`expr 1200 / $5`
PREV5=`expr 1500 / $5`

MODEL="<monitoringRules xmlns=\"http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema\">
  <monitoringRule id=\"cpuRule\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"VM\" type=\"Frontend\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"CPUUtilization\">
      <parameter name=\"samplingProbability\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction=\"Average\" groupingClass=\"VM\"/>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">FrontendCPUUtilization</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"cpuStealRule\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"VM\" type=\"Frontend\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"CPUStolen\">
      <parameter name=\"samplingProbability\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction=\"Average\" groupingClass=\"VM\"/>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">FrontendCPUStolen</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"respTimeRule\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\" type=\"getPage\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"EffectiveResponseTime\">
      <parameter name=\"samplingProbability\">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction=\"Average\" groupingClass=\"Method\"/>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">AvarageEffectiveResponseTime</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"sdaHaproxy\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"Estimation$4_AvarageEffectiveResponseTime\">
      <parameter name=\"window\">60</parameter>
      <parameter name=\"nCPU\">$3</parameter>
      <parameter name=\"CPUUtilTarget\">HTTPAgentHelper</parameter>
      <parameter name=\"CPUUtilMetric\">FrontendCPUUtilization</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
      <parameter name=\"filePath\">/home/ubuntu/modaclouds-sda/</parameter>
    </collectedMetric>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">EstimatedDemand</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"sdaForecastFirst\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"ForecastingTimeseriesARIMA_Workload_5Min\">
      <parameter name=\"order\">1</parameter>
      <parameter name=\"forecastPeriod\">$PREV1</parameter>
      <parameter name=\"autoregressive\">1</parameter>
      <parameter name=\"movingAverage\">1</parameter>
      <parameter name=\"integrated\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">ForecastedWorkload1</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"sdaForecastSecond\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"ForecastingTimeseriesARIMA_Workload_10Min\">
      <parameter name=\"order\">1</parameter>
      <parameter name=\"forecastPeriod\">$PREV2</parameter>
      <parameter name=\"autoregressive\">1</parameter>
      <parameter name=\"movingAverage\">1</parameter>
      <parameter name=\"integrated\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">ForecastedWorkload2</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"sdaForecastThird\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"ForecastingTimeseriesARIMA_Workload_15Min\">
      <parameter name=\"order\">1</parameter>
      <parameter name=\"forecastPeriod\">$PREV3</parameter>
      <parameter name=\"autoregressive\">1</parameter>
      <parameter name=\"movingAverage\">1</parameter>
      <parameter name=\"integrated\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">ForecastedWorkload3</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"sdaForecastFourth\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"ForecastingTimeseriesARIMA_Workload_20Min\">
      <parameter name=\"order\">1</parameter>
      <parameter name=\"forecastPeriod\">$PREV4</parameter>
      <parameter name=\"autoregressive\">1</parameter>
      <parameter name=\"movingAverage\">1</parameter>
      <parameter name=\"integrated\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">ForecastedWorkload4</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"sdaForecastFifth\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"ForecastingTimeseriesARIMA_Workload_25Min\">
      <parameter name=\"order\">1</parameter>
      <parameter name=\"forecastPeriod\">$PREV5</parameter>
      <parameter name=\"autoregressive\">1</parameter>
      <parameter name=\"movingAverage\">1</parameter>
      <parameter name=\"integrated\">1</parameter>
      <parameter name=\"samplingTime\">$5</parameter>
    </collectedMetric>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">ForecastedWorkload5</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id=\"workloadRule\" timeStep=\"$5\" timeWindow=\"$5\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\" type=\"getPage\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"EffectiveResponseTime\">
      <parameter name=\"samplingProbability\">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction=\"Count\" groupingClass=\"Method\"/>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">Workload</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
</monitoringRules>"

echo "$MODEL" | curl -X POST -i -H "Content-type: application/xml" http://"$1":8170/v1/monitoring-rules -d @-

JSON_INIT="{
    \"format\": \"TOWER/JSON\",
    \"protocol\": \"HTTP\",
    \"callbackUrl\": \"http://"$2":"

JSON_END="/data\"
}"

echo "$JSON_INIT"8178"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/AvarageEffectiveResponseTime/observers -d @-
echo "$JSON_INIT"8173"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/FrontendCPUUtilization/observers -d @-
echo "$JSON_INIT"8174"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/FrontendCPUStolen/observers -d @-
echo "$JSON_INIT"8179"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/EstimatedDemand/observers -d @-
echo "$JSON_INIT"8180"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload1/observers -d @-
echo "$JSON_INIT"8181"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload2/observers -d @-
echo "$JSON_INIT"8182"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload3/observers -d @-
echo "$JSON_INIT"8183"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload4/observers -d @-
echo "$JSON_INIT"8184"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload5/observers -d @-
echo "$JSON_INIT"8177"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/Workload/observers -d @-
