#!/bin/bash

instance_id=$(curl http://169.254.169.254/latest/meta-data/instance-id)
echo $instance_id
aws elb deregister-instances-from-load-balancer --load-balancer-name $1 --instances $instance_id

