#!/bin/bash

cd

rm .bashrc_mic
touch .bashrc_mic

if [ -z ${BASHRC_SET+x} ]
then
    echo "source .bashrc_mic" >> ~/.bashrc
    echo "export BASHRC_SET=true" >> ~/.bashrc
fi

bash ~/installMIC
bash ~/installImperialDC

cd
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
