#!/bin/bash

cd

MIC_DIST_LOCATION="https://github.com/deib-polimi/mic-frontend.git"
MIC_DIST_BRANCH="modaclouds-integration"
CPIM_DIST_LOCATION="https://github.com/deib-polimi/modaclouds-cpim-library.git"
CPIM_DIST_BRANCH="master"

echo "export MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_ID=mic-frontend-mon" >> ~/.bashrc_mic
echo "export MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_TYPE=Mic" >> ~/.bashrc_mic
echo "export MODACLOUDS_TOWER4CLOUDS_VM_ID=MIC" >> .bashrc_mic
echo "export MODACLOUDS_TOWER4CLOUDS_VM_TYPE=Frontend" >> .bashrc_mic
echo "export MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_TYPE=IaaS" >> .bashrc_mic
source ~/.bashrc_mic

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
sudo apt-get install build-essential -y

sudo apt-get install maven git -y

export M2_HOME=/usr/share/maven
echo "export M2_HOME=/usr/share/maven" >> ~/.bashrc_mic
export M2=$M2_HOME/bin
echo "export M2=\$M2_HOME/bin" >> ~/.bashrc_mic
export PATH=$M2:$PATH
echo "export PATH=\$M2:\$PATH" >> ~/.bashrc_mic

sudo apt-get install default-jre -q -y
export JAVA_HOME=/usr/lib/jvm/default-java
echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc_mic
source ~/.bashrc_mic

cd
sudo rm -rf modaclouds-cpim-library
git clone $CPIM_DIST_LOCATION -b $CPIM_DIST_BRANCH
cd modaclouds-cpim-library
mvn clean install -DskipTests -U

cd
sudo rm -rf mic-frontend
git clone $MIC_DIST_LOCATION -b $MIC_DIST_BRANCH
cd mic-frontend
mvn clean package -DskipTests -U

cp -R ~/mic-frontend/target/mic-frontend-* ~/
rm -rf ~/mic-frontend-*.war
rm -rf ~/mic_unzip
mv ~/mic-frontend-* ~/mic_unzip
mkdir -p ~/mic_unzip/WEB-INF/classes/META-INF

cd
source .bashrc_mic
