#!/bin/bash
#$1=MIC-IP

rm -f ~/mysql_help
touch ~/mysql_help
echo 'drop database if exists mic_db;
drop database if exists mic_blobdb;
use mysql;
delete u from user u where u.User="'"deib-polimi"'";
create database mic_db;
create database mic_blobdb;
create user "'"deib-polimi"'"@'$1' identified by "'"deib-polimi"'";
grant all on mic_db.* to "'"deib-polimi"'"@'$1';
grant all on mic_blobdb.* to "'"deib-polimi"'"@'$1';
' >> ~/mysql_help
mysql -uroot -proot < ~/mysql_help
exit

