#!/bin/bash
#$1=DB-IP
#$2=MP-IP
#$3=PROVIDER

PROVIDER="amazon"
if [ "$#" -gt 0 ]
then
    PROVIDER=$1
fi

cd ~/glassfish4/bin/
sudo ./asadmin stop-domain domain1
sudo rm ~/glassfish4/glassfish/domains/domain1/logs/*

cd
rm -f nohup-glass.out
bash ~/micwar_builder "$1"
bash ~/updateGlassfish_script "$1" "$2"

echo "export MODACLOUDS_TOWER4CLOUDS_MANAGER_IP=$2" >> ~/.bashrc_mic
echo "export MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_ID=$PROVIDER" >> .bashrc_mic

source ~/.bashrc_mic

cd ~/glassfish4/bin/
./asadmin undeploy mic-frontend-mon
./asadmin deploy /home/ubuntu/mic-frontend-mon.war
cd
