#!/bin/bash
#$1=DB IP
#$2=MP IP
#$3=MP PORT
#$4=PROVIDER

PORT="8170"
if [ "$#" -gt 2 ]
then
    PORT=$3
fi

PROVIDER="amazon"
if [ "$#" -gt 3 ]
then
    PROVIDER=$4
fi

cd ~/glassfish4/bin/
sudo ./asadmin stop-domain domain1
sudo rm ~/glassfish4/glassfish/domains/domain1/logs/*

cd
rm -f nohup-glass.out
bash ~/micwar_builder "$1"
bash ~/updateGlassfish_script "$1" "$2"

echo "export MODACLOUDS_TOWER4CLOUDS_MANAGER_IP=$2" >> ~/.bashrc_mic
echo "export MODACLOUDS_TOWER4CLOUDS_MANAGER_PORT=$PORT" >> ~/.bashrc_mic
if [ -z ${MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_ID+x} ]
then
    echo "export MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_ID=$PROVIDER" >> ~/.bashrc_mic
fi

source ~/.bashrc_mic

cd ~/glassfish4/bin/
./asadmin undeploy mic-frontend-mon
./asadmin deploy /home/ubuntu/mic-frontend-mon.war
cd

sleep 10

bash startImperialDC
