#!/bin/bash

cd ~/modaclouds-cpim-library
git pull
mvn clean install -DskipTests -U

cd ~/mic-frontend
git pull
mvn clean package -U

cp -R ~/mic-frontend/target/mic-frontend-* ~/
rm -rf ~/mic-frontend-*.war
rm -rf ~/mic_unzip
mv ~/mic-frontend-* ~/mic_unzip
mkdir -p ~/mic_unzip/WEB-INF/classes/META-INF

cd
