#!/bin/bash
#$1=MP-IP
#$2=OBSERVER-IP
#$3=OBSERVER-PORT

MODEL="<monitoringRules xmlns=\"http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema\">
  <monitoringRule id=\"respTimeRule\" timeStep=\"2\" timeWindow=\"10\">
    <monitoredTargets>
      <monitoredTarget class=\"Method\" type=\"getPage\"/>
    </monitoredTargets>
    <collectedMetric metricName=\"EffectiveResponseTime\">
      <parameter name=\"samplingProbability\">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction=\"Average\" groupingClass=\"Method\"/>
    <actions>
      <action name=\"OutputMetric\">
        <parameter name=\"metric\">AvarageEffectiveResponseTime</parameter>
        <parameter name=\"value\">METRIC</parameter>
        <parameter name=\"resourceId\">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
</monitoringRules>"

echo "$MODEL" | curl -X POST -i -H "Content-type: application/xml" http://"$1":8170/v1/monitoring-rules -d @-

JSON_INIT="{
    \"format\": \"TOWER/JSON\",
    \"protocol\": \"HTTP\",
    \"callbackUrl\": \"http://"$2":"

JSON_END="/data\"
}"

echo "$JSON_INIT$3$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/AvarageEffectiveResponseTime/observers -d @-
