#!/bin/sh

mkdir -p /home/ubuntu/git
rm -rf /home/ubuntu/git/*
cd /home/ubuntu/git && git clone https://github.com/deib-polimi/modaclouds-cpim-library.git
cd /home/ubuntu/git && git clone https://github.com/deib-polimi/mic-frontend.git -b modaclouds-integration
cd /home/ubuntu/git/modaclouds-cpim-library && mvn clean install -DskipTests
cd /home/ubuntu/git/mic-frontend && mvn clean package
cp -R /home/ubuntu/git/mic-frontend/target/mic-frontend-* /home/ubuntu/
rm -rf /home/ubuntu/mic-frontend-*.war
rm -rf /home/ubuntu/mic_unzip
mv /home/ubuntu/mic-frontend-* /home/ubuntu/mic_unzip
