#!/bin/bash
#$1=MP-IP
#$2=SDA-IP

curl -X POST -i -H "Content-type: application/xml" http://"$1":8170/v1/monitoring-rules -d '
<monitoringRules xmlns="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema">
  <monitoringRule id="cpuRule" timeStep="3" timeWindow="3">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="CPUUtilization">
      <parameter name="samplingProbability">1</parameter>
      <parameter name="samplingTime">3</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Average" groupingClass="VM"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">FrontendCPUUtilization</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="cpuStealRule" timeStep="3" timeWindow="3">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="CPUStolen">
      <parameter name="samplingProbability">1</parameter>
      <parameter name="samplingTime">3</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Average" groupingClass="VM"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">FrontendCPUStolen</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="respTimeRule" timeStep="2" timeWindow="10">
    <monitoredTargets>
      <monitoredTarget class="Method" type="answerQuestions"/>
      <monitoredTarget class="Method" type="saveAnswers"/>
      <monitoredTarget class="Method" type="register"/>
    </monitoredTargets>
    <collectedMetric metricName="EffectiveResponseTime">
      <parameter name="samplingProbability">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Average" groupingClass="Method"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">AvarageEffectiveResponseTime</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="sdaHaproxy" timeStep="300" timeWindow="300">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="EstimationCI">
      <parameter name="window">60000</parameter>
      <parameter name="nCPU">2</parameter>
      <parameter name="CPUUtilTarget">MIC</parameter>
      <parameter name="CPUUtilMetric">FrontendCPUUtilization</parameter>
      <parameter name="targetMetric">AvarageEffectiveResponseTime</parameter>
      <parameter name="samplingTime">300</parameter>
      <parameter name="filePath">/home/ubuntu/modaclouds-sda-1.2.2/</parameter>
    </collectedMetric>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">EstimatedDemand</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="sdaForecastFirst" timeStep="300" timeWindow="300">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="ForecastingTimeSeriesARIMA5Min">
      <parameter name="targetMetric">Workload</parameter>
      <parameter name="forecastPeriod">30</parameter>
      <parameter name="autoregressive">1</parameter>
      <parameter name="movingAverage">1</parameter>
      <parameter name="integrated">1</parameter>
      <parameter name="samplingTime">300</parameter>
    </collectedMetric>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">ForecastedWorkload1</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="sdaForecastSecond" timeStep="300" timeWindow="300">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="ForecastingTimeSeriesARIMA10Min">
      <parameter name="targetMetric">Workload</parameter>
      <parameter name="forecastPeriod">60</parameter>
      <parameter name="autoregressive">1</parameter>
      <parameter name="movingAverage">1</parameter>
      <parameter name="integrated">1</parameter>
      <parameter name="samplingTime">300</parameter>
    </collectedMetric>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">ForecastedWorkload2</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="sdaForecastThird" timeStep="300" timeWindow="300">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="ForecastingTimeSeriesARIMA15Min">
      <parameter name="targetMetric">Workload</parameter>
      <parameter name="forecastPeriod">90</parameter>
      <parameter name="autoregressive">1</parameter>
      <parameter name="movingAverage">1</parameter>
      <parameter name="integrated">1</parameter>
      <parameter name="samplingTime">300</parameter>
    </collectedMetric>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">ForecastedWorkload3</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="sdaForecastFourth" timeStep="300" timeWindow="300">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="ForecastingTimeSeriesARIMA20Min">
      <parameter name="targetMetric">Workload</parameter>
      <parameter name="forecastPeriod">120</parameter>
      <parameter name="autoregressive">1</parameter>
      <parameter name="movingAverage">1</parameter>
      <parameter name="integrated">1</parameter>
      <parameter name="samplingTime">300</parameter>
    </collectedMetric>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">ForecastedWorkload4</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="sdaForecastFifth" timeStep="300" timeWindow="300">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="ForecastingTimeSeriesARIMA25Min">
      <parameter name="targetMetric">Workload</parameter>
      <parameter name="forecastPeriod">150</parameter>
      <parameter name="autoregressive">1</parameter>
      <parameter name="movingAverage">1</parameter>
      <parameter name="integrated">1</parameter>
      <parameter name="samplingTime">300</parameter>
    </collectedMetric>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">ForecastedWorkload5</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="workloadRule" timeStep="10" timeWindow="10">
    <monitoredTargets>
      <monitoredTarget class="Method" type="answerQuestions"/>
      <monitoredTarget class="Method" type="saveAnswers"/>
      <monitoredTarget class="Method" type="register"/>
    </monitoredTargets>
    <collectedMetric metricName="EffectiveResponseTime">
      <parameter name="samplingProbability">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Count" groupingClass="Method"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">Workload</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
</monitoringRules>
'

JSON_INIT="{
    \"format\": \"TOWER/JSON\",
    \"protocol\": \"HTTP\",
    \"callbackUrl\": \"http://"$2":"

JSON_END="/v1/results\"
}"

echo "$JSON_INIT"8178"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/AvarageEffectiveResponseTime/observers -d @-
echo "$JSON_INIT"8177"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/FrontendCPUUtilization/observers -d @-
echo "$JSON_INIT"8173"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/FrontendCPUStolen/observers -d @-
echo "$JSON_INIT"8179"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/EstimatedDemand/observers -d @-
echo "$JSON_INIT"8185"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload1/observers -d @-
echo "$JSON_INIT"8180"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload2/observers -d @-
echo "$JSON_INIT"8181"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload3/observers -d @-
echo "$JSON_INIT"8182"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload4/observers -d @-
echo "$JSON_INIT"8183"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/ForecastedWorkload5/observers -d @-
echo "$JSON_INIT"8174"$JSON_END" | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/Workload/observers -d @-
