#!/bin/bash
#$1=MP-IP

curl -X POST -i -H "Content-type: application/xml" http://"$1":8170/v1/monitoring-rules -d '
<monitoringRules xmlns="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema">
  <monitoringRule id="cpuRule" timeStep="3" timeWindow="3">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="CPUUtilization">
      <parameter name="samplingProbability">1</parameter>
      <parameter name="samplingTime">3</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Average" groupingClass="VM"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">FrontendCPUUtilization</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
<monitoringRule id="cpuStealRule" timeStep="3" timeWindow="3">
    <monitoredTargets>
      <monitoredTarget class="VM" type="Frontend"/>
    </monitoredTargets>
    <collectedMetric metricName="CPUStolen">
      <parameter name="samplingProbability">1</parameter>
      <parameter name="samplingTime">3</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Average" groupingClass="VM"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">FrontendCPUStolen</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="respTimeRule" timeStep="2" timeWindow="10">
    <monitoredTargets>
      <monitoredTarget class="Method" type="answerQuestions"/>
      <monitoredTarget class="Method" type="saveAnswers"/>
      <monitoredTarget class="Method" type="register"/>
    </monitoredTargets>
    <collectedMetric metricName="EffectiveResponseTime">
      <parameter name="samplingProbability">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Average" groupingClass="Method"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">AvarageEffectiveResponseTime</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
  <monitoringRule id="workloadRule" timeStep="10" timeWindow="10">
    <monitoredTargets>
      <monitoredTarget class="Method" type="answerQuestions"/>
      <monitoredTarget class="Method" type="saveAnswers"/>
      <monitoredTarget class="Method" type="register"/>
    </monitoredTargets>
    <collectedMetric metricName="EffectiveResponseTime">
      <parameter name="samplingProbability">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Count" groupingClass="Method"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">Workload</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
</monitoringRules>
'
curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/AvarageEffectiveResponseTime/observers -d '
{
    "format": "RDF/JSON",
    "protocol": "HTTP",
    "callbackUrl": "http://$1:8001"
}
' 
curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/FrontendCPUUtilization/observers -d '
{
    "format": "RDF/JSON",
    "protocol": "HTTP",
    "callbackUrl": "http://$1:8001"
}
' 
curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/FrontendCPUStolen/observers -d '
{
    "format": "RDF/JSON",
    "protocol": "HTTP",
    "callbackUrl": "http://$1:8001"
}
'
curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/Workload/observers -d '
{
    "format": "RDF/JSON",
    "protocol": "HTTP",
    "callbackUrl": "http://$1:8001"
}
'