#!/bin/bash
#$1=MP-IP

curl -X POST -i -H "Content-type: application/xml" http://"$1":8170/v1/monitoring-rules -d '
<monitoringRules xmlns="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.modaclouds.eu/xsd/1.0/monitoring_rules_schema">
  <monitoringRule id="respTimeRule" timeStep="1" timeWindow="1">
    <monitoredTargets>
      <monitoredTarget class="Method" type="answerQuestions"/>
      <monitoredTarget class="Method" type="saveAnswers"/>
      <monitoredTarget class="Method" type="register"/>
    </monitoredTargets>
    <collectedMetric metricName="ResponseTime">
      <parameter name="samplingProbability">1</parameter>
    </collectedMetric>
    <metricAggregation aggregateFunction="Count" groupingClass="Method"/>
    <actions>
      <action name="OutputMetric">
        <parameter name="metric">CountResponseTime</parameter>
        <parameter name="value">METRIC</parameter>
        <parameter name="resourceId">ID</parameter>
      </action>
    </actions>
  </monitoringRule>
</monitoringRules>
'

JSON="{
    \"format\": \"TOWER/JSON\",
    \"protocol\": \"HTTP\",
    \"callbackUrl\": \"http://localhost:8001/data\"
}"

exec echo $JSON | curl -X POST -i -H "Content-type: application/json" http://"$1":8170/v1/metrics/CountResponseTime/observers -d @-
