#!/bin/bash
#$1=SDA-IP
#$2=KEY
#$3=USER

ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8177 > cpu.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8173 > cpuSteal.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8178 > rt.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8179 > d.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8185 > wlforFirst.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8180 > wlforSecond.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8181 > wlforThird.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8182 > wlforFourth.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8183 > wlforFifth.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8174 > wl.out 2>&1 &'
ssh -i $2 -o StrictHostKeyChecking=no $3@"$1" 'nohup java -jar testObserver.jar 8184 > thresholds.out 2>&1 &'
