#!/bin/bash

cd

sudo apt-get update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
sudo apt-get install build-essential -y

sudo apt-get install default-jre -q -y
export JAVA_HOME=/usr/lib/jvm/default-java
echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc_mpl

rm -rf MCR
mkdir MCR
cd MCR

wget http://it.mathworks.com/supportfiles/MCR_Runtime/R2013a/MCR_R2013a_glnxa64_installer.zip
unzip MCR_R2013a_glnxa64_installer.zip
sudo ./install -mode silent -agreeToLicense yes

sudo rm -rf /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre
sudo ln -s /usr/lib/jvm/default-java/jre /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre

wget http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.jar
sudo rm /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/java/jarext/axis2/httpcore.jar
sudo ln -s /home/ubuntu/MCR/httpcore-4.4.1.jar /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/java/jarext/axis2/httpcore.jar

cd
rm -rf modaclouds-sda
mkdir modaclouds-sda
cd modaclouds-sda
# wget modaclouds-sda
# tar xf file

cd ~/modaclouds-sda
git clone https://github.com/deib-polimi/Modaclouds-SDASync.git
cd Modaclouds-SDASync
mvn clean package assembly:assembly -U
mv target/sdaSync*.jar ~/modaclouds-sda/lib/

echo "export MODACLOUDS_TOWER4CLOUDS_MANAGER_IP=localhost" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_MANAGER_PORT=8170" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_ID=mic-frontend-mon" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_INTERNAL_COMPONENT_TYPE=Mic" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_VM_ID=MIC" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_VM_TYPE=Frontend" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_ID=amazon" >> ~/.bashrc_mpl
echo "export MODACLOUDS_TOWER4CLOUDS_CLOUD_PROVIDER_TYPE=IaaS" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MONITORING_DDA_ENDPOINT_IP=localhost" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MONITORING_DDA_ENDPOINT_PORT=8175" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MATLAB_SDA_IP=localhost" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MATLAB_SDA_PORT=8176" >> ~/.bashrc_mpl
echo "export MODACLOUDS_JAVA_SDA_IP=localhost" >> ~/.bashrc_mpl
echo "export MODACLOUDS_JAVA_SDA_PORT=8177" >> ~/.bashrc_mpl
echo "export MODACLOUDS_WEKA_SDA_IP=localhost" >> ~/.bashrc_mpl
echo "export MODACLOUDS_WEKA_SDA_PORT=8177" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MONITORING_MANAGER_PORT=8170" >> ~/.bashrc_mpl

source ~/.bashrc_mpl
cd
