#!/bin/bash

cd

rm .bashrc_mpl
touch .bashrc_mpl

if [ -z ${BASHRC_SET+x} ]
then
    echo "source .bashrc_mpl" >> ~/.bashrc
    echo "export BASHRC_SET=true" >> ~/.bashrc
fi

bash ~/installPlatform
bash ~/installSDA

cd
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
