#!/bin/bash

echo "export MODACLOUDS_TOWER4CLOUDS_MANAGER_IP=$1" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MONITORING_DDA_ENDPOINT_IP=$1" >> ~/.bashrc_mpl
echo "export MODACLOUDS_MATLAB_SDA_IP=$1" >> ~/.bashrc_mpl
echo "export MODACLOUDS_JAVA_SDA_IP=$1" >> ~/.bashrc_mpl
echo "export MODACLOUDS_WEKA_SDA_IP=$1" >> ~/.bashrc_mpl

cd /home/ubuntu/modaclouds-sda
source ~/.bashrc_mpl
sudo -E nohup bash run_main.sh /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81 tower4clouds > /home/ubuntu/sda.out 2>&1 &

cd
