#!/bin/sh

export SCALINGRULES_HOME="${SCALINGRULES_HOME:-$PWD}"

if [ ! -e "$SCALINGRULES_HOME" ]
then
    echo "$SCALINGRULES_HOME does not exist" 1>&2
    exit 1
fi

JAR="$SCALINGRULES_HOME/scalingrules.jar"
CLASS="it.polimi.modaclouds.scalingrules.Main"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    SCALINGRULES_HOME=`cygpath -w "$SCALINGRULES_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

#exec java  $JVM_ARGS -jar "$JAR" "$@"
exec java $JVM_ARGS -cp "$JAR" "$CLASS" "$@"