#!/bin/sh

export CLOUDMLDAEMON_HOME="${CLOUDMLDAEMON_HOME:-$PWD}"

if [ ! -e "$CLOUDMLDAEMON_HOME" ]
then
    echo "$CLOUDMLDAEMON_HOME does not exist" 1>&2
    exit 1
fi

JAR="$CLOUDMLDAEMON_HOME/cloudmldaemon.jar"

if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    CLOUDMLDAEMON_HOME=`cygpath -w "$CLOUDMLDAEMON_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

exec java $JVM_ARGS -jar "$JAR" "$@" &
